### ISSUE TITLE
PR to also detect translation languages?

### ISSUE THREAD

**Issue by DuncanMacWeb** [ClaudiuCeia/detect-translation#2]
Hi @ClaudiuCeia! Love this repo, great work!

Would you be interested in a PR to detect which natural language the page is translated into even if the translator hasn’t changed the `lang` attribute to say so (which includes many translators, including Papago and most Chinese ones; also many common browser extensions)?

I’ve written some code that does this and should be able to contribute it. It also detects additional translators, including more Chinese ones (Caiyun, QQ Browser, Sogou and Youdao) and can output a language tag like `zh-t-en-t0-baidu` (using the [BCP 47 T extension](https://www.unicode.org/reports/tr35/#t_Extension)) indicating that the content is translated and by which translation service, which is useful for analytics.

The natural language detection is very lightweight (1–2 KB) and uses substrings unique to each language, produced from known translations of a phrase. The source phrase I have used is “Skip to main content”, which is present on many sites as it is [a recommended technique](https://www.w3.org/TR/WCAG20-TECHS/G1.html#G1-ex2) to meet the [WCAG 2.1 accessibility requirement 2.4.1 Bypass Blocks](https://www.w3.org/TR/WCAG21/#bypass-blocks). (The algorithm can also produce unique substrings for translations of any other phrase, of course.)

Let me know if you would like a PR!

**Comment by ClaudiuCeia** [comment]
Hey @DuncanMacWeb - very sorry for the delay answering this. I haven't been active on GitHub this month and I didn't expect people stumbling upon my repos :) 

I'm definitely interested in contributions, and to be honest, it sounds like you know much more about this than I do. I only built this as I had a real need to see what languages people translate some COVID-19 guides to, so we prioritize i18n work. 

Feel free to send a PR or let me know how you'd like to do this. Happy to add you as a maintainer as well.
