### ISSUE TITLE
Releasing new NPM versions

### ISSUE THREAD

**Issue by DuncanMacWeb** [ClaudiuCeia/detect-translation#6]
Hi @ClaudiuCeia, hope you are well?

I’ve been thinking about our work on this repo and I’m excited about making further improvements! We really need a streamlined way of doing releases, though. Would you be able to do a Zoom/Jitsi call to discuss? If you don’t have capacity to do releases at the moment, I would be happy to share responsibility for that.

Best,
Duncan

**Comment by DuncanMacWeb** [comment]
Update: my NPM username is duncanmacweb, if you would like to add me as a maintainer there too, I can take care of publishing new versions :)

**Comment by ClaudiuCeia** [comment]
Hi @DuncanMacWeb,

I've done pretty bad keeping this going. You have an invite on npm and I just pushed a commit to bring dependencies up to date. Not much required changes but you'll notice that `services.test.ts` is gone. 

This contained the tests for IBM Watson and they were failing, I'm not really sure why but I also wanted to get this out of the gate for now and let you know that it's your call what you want to do further (continue as a maintainer here, do a hard fork, etc). 

Sorry again and hope you've done well through the pandemic. 

Cheers

**Comment by DuncanMacWeb** [comment]
Hey @ClaudiuCeia, thanks and hope you’ve been well also. Really appreciate that. All best wishes.

**Comment by jessetan** [comment]
Hi @ClaudiuCeia @DuncanMacWeb, reviving this old thread. Is any new release planned? The version on npm is still 0.0.4, while this repo contains a 0.1.1 tag
